//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotePadCalendar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promt
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Data { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
    }
}
